[source]
type = "N2C"
address = ["Unix", "/node-ipc/node.socket"]
magic = "mainnet"

[source.intersect]
type = "Point"
value = [
    47931310,
    "89f93419845d5f6ce8040fd5eeedda93d764c8569f7c2cc6802a8429a0da877b"
]

[[filters]]
type = "Selection"


[filters.check]
predicate = "all_of"

[[filters.check.argument]]
predicate = "variant_in"
argument = ["Mint"]

[[filters.check.argument]]
predicate = "policy_equals"
argument = "f0ff48bbb7bbe9d59a40f1ce90e9e9d0ff5002ec48f232b49ca0fb9a"

[sink]
type = "Logs"
output_format = "JSONL"
output_path = "/logoutput/ouralogs"
max_bytes_per_file = 1_000_000
